name: log_manager_plugin
description: A comprehensive Flutter logging plugin with console output, file storage, log viewer UI, compression, and upload capabilities. Supports Dio interceptor and date-based log management.
version: 1.1.0
homepage: https://github.com/xiaoli55979/log_manager_plugin
repository: https://github.com/xiaoli55979/log_manager_plugin
issue_tracker: https://github.com/xiaoli55979/log_manager_plugin/issues

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  logger: ^2.6.2
  dio: ^5.9.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  archive: ^4.0.9
  flutter_highlight: ^0.7.0
  share_plus: ^12.0.1

dev_dependencies:
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
